// features24.vue
<template>
  <div class="thq-section-padding">
    <div class="features24-container2 thq-section-max-width">
      <div class="features24-image-container">
        <img
          :alt="feature1ImgAlt"
          :src="feature1ImgSrc"
          v-if="activeTab === 0"
          class="features24-image1 thq-img-ratio-16-9"
        />
        <img
          :alt="feature2ImgAlt"
          :src="feature2ImgSrc"
          v-if="activeTab === 1"
          class="features24-image2 thq-img-ratio-16-9"
        />
        <img
          :alt="feature3ImgAlt"
          :src="feature3ImgSrc"
          v-if="activeTab === 2"
          class="features24-image3 thq-img-ratio-16-9"
        />
      </div>
      <div class="features24-tabs-menu">
        <div @click="activeTab = 0" class="features24-tab-horizontal1">
          <div class="features24-divider-container1">
            <div v-if="activeTab === 0" class="features24-container3"></div>
          </div>
          <div class="features24-content1">
            <h2>
              <slot name="feature1Title">
                <!--Default content for feature1Title-->
                <div class="features24-fragment4">
                  <h2 class="features24-text4 thq-heading-2">
                    Professional Websites
                  </h2>
                </div>
              </slot>
            </h2>
            <span>
              <slot name="feature1Description">
                <!--Default content for feature1Description-->
                <div class="features24-fragment5">
                  <span class="features24-text5 thq-body-small">
                    High-Quality Websites
                  </span>
                </div>
              </slot>
            </span>
          </div>
        </div>
        <div @click="activeTab = 1" class="features24-tab-horizontal2">
          <div class="features24-divider-container2">
            <div v-if="activeTab === 1" class="features24-container4"></div>
          </div>
          <div class="features24-content2">
            <h2>
              <slot name="feature2Title">
                <!--Default content for feature2Title-->
                <div class="features24-fragment6">
                  <h2 class="features24-text6 thq-heading-2">
                    Mobile-Friendly Designs
                  </h2>
                </div>
              </slot>
            </h2>
            <span>
              <slot name="feature2Description">
                <!--Default content for feature2Description-->
                <div class="features24-fragment3">
                  <span class="features24-text3 thq-body-small">
                    Responsive Layouts
                  </span>
                </div>
              </slot>
            </span>
          </div>
        </div>
        <div @click="activeTab = 2" class="features24-tab-horizontal3">
          <div class="features24-divider-container3">
            <div v-if="activeTab === 2" class="features24-container5"></div>
          </div>
          <div class="features24-content3">
            <h2>
              <slot name="feature3Title">
                <!--Default content for feature3Title-->
                <div class="features24-fragment2">
                  <h2 class="features24-text2 thq-heading-2">Unique Designs</h2>
                </div>
              </slot>
            </h2>
            <span>
              <slot name="feature3Description">
                <!--Default content for feature3Description-->
                <div class="features24-fragment1">
                  <span class="features24-text1 thq-body-small">
                    Customized Designs
                  </span>
                </div>
              </slot>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Features24',
  props: {
    feature1ImgAlt: {
      type: String,
      default: 'Website Creation',
    },
    feature3ImgSrc: {
      type: String,
      default:
        'https://images.unsplash.com/photo-1632823469121-218dce1a15f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0N3w&ixlib=rb-4.0.3&q=80&w=1080',
    },
    feature1ImgSrc: {
      type: String,
      default:
        'https://images.unsplash.com/photo-1701009796009-381d273bd38a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0OHw&ixlib=rb-4.0.3&q=80&w=1080',
    },
    feature3ImgAlt: {
      type: String,
      default: 'Custom Designs',
    },
    feature2ImgSrc: {
      type: String,
      default:
        'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0OHw&ixlib=rb-4.0.3&q=80&w=1080',
    },
    feature2ImgAlt: {
      type: String,
      default: 'Responsive Layout',
    },
  },
  data() {
    return {
      activeTab: 0,
    }
  },
}
</script>

<style scoped>
.features24-container2 {
  width: 100%;
  display: grid;
  grid-gap: var(--dl-space-space-fiveunits);
  position: relative;
  grid-template-columns: 1fr 1fr;
}
.features24-image-container {
  height: 100%;
  display: flex;
  position: relative;
}
.features24-image1 {
  animation-name: fadeIn;
  animation-delay: 0s;
  animation-duration: 300ms;
  animation-direction: normal;
  animation-iteration-count: 1;
  animation-timing-function: ease;
}
.features24-image2 {
  animation-name: fadeIn;
  animation-delay: 0s;
  animation-duration: 300ms;
  animation-direction: normal;
  animation-iteration-count: 1;
  animation-timing-function: ease;
}
.features24-image3 {
  animation-name: fadeIn;
  animation-delay: 0s;
  animation-duration: 300ms;
  animation-direction: normal;
  animation-iteration-count: 1;
  animation-timing-function: ease;
}
.features24-tabs-menu {
  gap: var(--dl-space-space-twounits);
  width: 100%;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  justify-content: center;
}
.features24-tab-horizontal1 {
  gap: var(--dl-space-space-twounits);
  cursor: pointer;
  display: flex;
  overflow: hidden;
  align-self: stretch;
  align-items: flex-start;
  flex-shrink: 0;
}
.features24-divider-container1 {
  display: flex;
  align-self: stretch;
  align-items: flex-start;
}
.features24-container3 {
  width: 2px;
  align-self: stretch;
  background-color: var(--dl-color-theme-neutral-dark);
}
.features24-content1 {
  gap: 16px;
  flex: 1;
  display: flex;
  overflow: hidden;
  flex-grow: 1;
  align-items: flex-start;
  flex-shrink: 0;
  flex-direction: column;
  justify-content: center;
}
.features24-tab-horizontal2 {
  gap: var(--dl-space-space-twounits);
  cursor: pointer;
  display: flex;
  overflow: hidden;
  align-self: stretch;
  align-items: flex-start;
  flex-shrink: 0;
}
.features24-divider-container2 {
  display: flex;
  align-self: stretch;
  align-items: flex-start;
}
.features24-container4 {
  width: 2px;
  align-self: stretch;
  background-color: var(--dl-color-theme-neutral-dark);
}
.features24-content2 {
  gap: 16px;
  flex: 1;
  display: flex;
  overflow: hidden;
  flex-grow: 1;
  align-items: flex-start;
  flex-shrink: 0;
  flex-direction: column;
  justify-content: center;
}
.features24-tab-horizontal3 {
  gap: var(--dl-space-space-twounits);
  cursor: pointer;
  display: flex;
  overflow: hidden;
  align-self: stretch;
  align-items: flex-start;
  flex-shrink: 0;
}
.features24-divider-container3 {
  display: flex;
  align-self: stretch;
  align-items: flex-start;
}
.features24-container5 {
  width: 2px;
  align-self: stretch;
  background-color: var(--dl-color-theme-neutral-dark);
}
.features24-content3 {
  gap: 16px;
  flex: 1;
  display: flex;
  overflow: hidden;
  flex-grow: 1;
  align-items: flex-start;
  flex-shrink: 0;
  flex-direction: column;
  justify-content: center;
}
.features24-fragment1 {
  display: contents;
}
.features24-text1 {
  display: inline-block;
}
.features24-fragment2 {
  display: contents;
}
.features24-text2 {
  display: inline-block;
}
.features24-fragment3 {
  display: contents;
}
.features24-text3 {
  display: inline-block;
}
.features24-fragment4 {
  display: contents;
}
.features24-text4 {
  display: inline-block;
}
.features24-fragment5 {
  display: contents;
}
.features24-text5 {
  display: inline-block;
}
.features24-fragment6 {
  display: contents;
}
.features24-text6 {
  display: inline-block;
}
@media(max-width: 991px) {
  .features24-container2 {
    grid-gap: var(--dl-space-space-twounits);
    grid-template-columns: 1fr;
  }
}
</style>

// features24.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-features24',
  templateUrl: 'features24.component.html',
  styleUrls: ['features24.component.css'],
})
export class Features24 {
  @Input()
  feature1ImgAlt: string = 'Website Creation'
  @ContentChild('feature3Description')
  feature3Description: TemplateRef<any>
  @ContentChild('feature3Title')
  feature3Title: TemplateRef<any>
  @Input()
  feature3ImgSrc: string =
    'https://images.unsplash.com/photo-1632823469121-218dce1a15f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0N3w&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  feature1ImgSrc: string =
    'https://images.unsplash.com/photo-1701009796009-381d273bd38a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0OHw&ixlib=rb-4.0.3&q=80&w=1080'
  @ContentChild('feature2Description')
  feature2Description: TemplateRef<any>
  @ContentChild('feature1Title')
  feature1Title: TemplateRef<any>
  @Input()
  feature3ImgAlt: string = 'Custom Designs'
  @ContentChild('feature1Description')
  feature1Description: TemplateRef<any>
  @Input()
  feature2ImgSrc: string =
    'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTcyNDk0MzM0OHw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  feature2ImgAlt: string = 'Responsive Layout'
  @ContentChild('feature2Title')
  feature2Title: TemplateRef<any>
  activeTab: number = 0
  constructor() {}
}

<div class="thq-section-padding">
  <div class="features24-container2 thq-section-max-width">
    <div class="features24-image-container">
      <img
        [attr.alt]="feature1ImgAlt"
        [attr.src]="feature1ImgSrc"
        *ngIf="activeTab === 0"
        class="features24-image1 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature2ImgAlt"
        [attr.src]="feature2ImgSrc"
        *ngIf="activeTab === 1"
        class="features24-image2 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature3ImgAlt"
        [attr.src]="feature3ImgSrc"
        *ngIf="activeTab === 2"
        class="features24-image3 thq-img-ratio-16-9"
      />
    </div>
    <div class="features24-tabs-menu">
      <div (click)="activeTab = 0" class="features24-tab-horizontal1">
        <div class="features24-divider-container1">
          <div *ngIf="activeTab === 0" class="features24-container3"></div>
        </div>
        <div class="features24-content1">
          <h2>
            <ng-container>
              <ng-template #defaultFeature1Title>
                <div class="features24-fragment4">
                  <h2 class="features24-text4 thq-heading-2">
                    Professional Websites
                  </h2>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Title ? feature1Title : defaultFeature1Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span>
            <ng-container>
              <ng-template #defaultFeature1Description>
                <div class="features24-fragment5">
                  <span class="features24-text5 thq-body-small">
                    High-Quality Websites
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Description ? feature1Description : defaultFeature1Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 1" class="features24-tab-horizontal2">
        <div class="features24-divider-container2">
          <div *ngIf="activeTab === 1" class="features24-container4"></div>
        </div>
        <div class="features24-content2">
          <h2>
            <ng-container>
              <ng-template #defaultFeature2Title>
                <div class="features24-fragment6">
                  <h2 class="features24-text6 thq-heading-2">
                    Mobile-Friendly Designs
                  </h2>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Title ? feature2Title : defaultFeature2Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span>
            <ng-container>
              <ng-template #defaultFeature2Description>
                <div class="features24-fragment3">
                  <span class="features24-text3 thq-body-small">
                    Responsive Layouts
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Description ? feature2Description : defaultFeature2Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 2" class="features24-tab-horizontal3">
        <div class="features24-divider-container3">
          <div *ngIf="activeTab === 2" class="features24-container5"></div>
        </div>
        <div class="features24-content3">
          <h2>
            <ng-container>
              <ng-template #defaultFeature3Title>
                <div class="features24-fragment2">
                  <h2 class="features24-text2 thq-heading-2">Unique Designs</h2>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Title ? feature3Title : defaultFeature3Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span>
            <ng-container>
              <ng-template #defaultFeature3Description>
                <div class="features24-fragment1">
                  <span class="features24-text1 thq-body-small">
                    Customized Designs
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Description ? feature3Description : defaultFeature3Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
